# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import recommender_pb2 as proto_dot_recommender__pb2


class RecommenderStub(object):
    """gRPC service for recommendation
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecommendations = channel.unary_unary(
                '/recommendation.Recommender/GetRecommendations',
                request_serializer=proto_dot_recommender__pb2.RecommendationRequest.SerializeToString,
                response_deserializer=proto_dot_recommender__pb2.RecommendationResponse.FromString,
                )


class RecommenderServicer(object):
    """gRPC service for recommendation
    """

    def GetRecommendations(self, request, context):
        """Method to get recommendations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendations,
                    request_deserializer=proto_dot_recommender__pb2.RecommendationRequest.FromString,
                    response_serializer=proto_dot_recommender__pb2.RecommendationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendation.Recommender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Recommender(object):
    """gRPC service for recommendation
    """

    @staticmethod
    def GetRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/recommendation.Recommender/GetRecommendations',
            proto_dot_recommender__pb2.RecommendationRequest.SerializeToString,
            proto_dot_recommender__pb2.RecommendationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
