# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/recommender.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/recommender.proto\x12\x0erecommendation\"E\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x1b\n\x13num_recommendations\x18\x02 \x01(\x05\"3\n\x16RecommendationResponse\x12\x19\n\x11recommended_items\x18\x01 \x03(\t2r\n\x0bRecommender\x12\x63\n\x12GetRecommendations\x12%.recommendation.RecommendationRequest\x1a&.recommendation.RecommendationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.recommender_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=43
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=112
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=114
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=165
  _globals['_RECOMMENDER']._serialized_start=167
  _globals['_RECOMMENDER']._serialized_end=281
# @@protoc_insertion_point(module_scope)
